//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 4 colors.
  struct color {
    /// Color `darkPurple`.
    static let darkPurple = Rswift.ColorResource(bundle: R.hostingBundle, name: "darkPurple")
    /// Color `goldenYellow`.
    static let goldenYellow = Rswift.ColorResource(bundle: R.hostingBundle, name: "goldenYellow")
    /// Color `navy-blue`.
    static let navyBlue = Rswift.ColorResource(bundle: R.hostingBundle, name: "navy-blue")
    /// Color `red-darker`.
    static let redDarker = Rswift.ColorResource(bundle: R.hostingBundle, name: "red-darker")
    
    /// `UIColor(named: "darkPurple", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func darkPurple(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.darkPurple, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "goldenYellow", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func goldenYellow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.goldenYellow, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "navy-blue", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func navyBlue(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.navyBlue, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "red-darker", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func redDarker(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.redDarker, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 9 images.
  struct image {
    /// Image `back`.
    static let back = Rswift.ImageResource(bundle: R.hostingBundle, name: "back")
    /// Image `church_logo`.
    static let church_logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "church_logo")
    /// Image `fire`.
    static let fire = Rswift.ImageResource(bundle: R.hostingBundle, name: "fire")
    /// Image `nav-discover`.
    static let navDiscover = Rswift.ImageResource(bundle: R.hostingBundle, name: "nav-discover")
    /// Image `next`.
    static let next = Rswift.ImageResource(bundle: R.hostingBundle, name: "next")
    /// Image `profile-add`.
    static let profileAdd = Rswift.ImageResource(bundle: R.hostingBundle, name: "profile-add")
    /// Image `profile_more`.
    static let profile_more = Rswift.ImageResource(bundle: R.hostingBundle, name: "profile_more")
    /// Image `profilepic_more`.
    static let profilepic_more = Rswift.ImageResource(bundle: R.hostingBundle, name: "profilepic_more")
    /// Image `welcome`.
    static let welcome = Rswift.ImageResource(bundle: R.hostingBundle, name: "welcome")
    
    /// `UIImage(named: "back", bundle: ..., traitCollection: ...)`
    static func back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "church_logo", bundle: ..., traitCollection: ...)`
    static func church_logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.church_logo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "fire", bundle: ..., traitCollection: ...)`
    static func fire(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fire, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "nav-discover", bundle: ..., traitCollection: ...)`
    static func navDiscover(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navDiscover, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "next", bundle: ..., traitCollection: ...)`
    static func next(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.next, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "profile-add", bundle: ..., traitCollection: ...)`
    static func profileAdd(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profileAdd, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "profile_more", bundle: ..., traitCollection: ...)`
    static func profile_more(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profile_more, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "profilepic_more", bundle: ..., traitCollection: ...)`
    static func profilepic_more(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.profilepic_more, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "welcome", bundle: ..., traitCollection: ...)`
    static func welcome(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.welcome, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 7 storyboards.
  struct storyboard {
    /// Storyboard `BibleStudy`.
    static let bibleStudy = _R.storyboard.bibleStudy()
    /// Storyboard `Giving`.
    static let giving = _R.storyboard.giving()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `LiveStream`.
    static let liveStream = _R.storyboard.liveStream()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `More`.
    static let more = _R.storyboard.more()
    /// Storyboard `Welcome`.
    static let welcome = _R.storyboard.welcome()
    
    /// `UIStoryboard(name: "BibleStudy", bundle: ...)`
    static func bibleStudy(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.bibleStudy)
    }
    
    /// `UIStoryboard(name: "Giving", bundle: ...)`
    static func giving(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.giving)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "LiveStream", bundle: ...)`
    static func liveStream(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.liveStream)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "More", bundle: ...)`
    static func more(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.more)
    }
    
    /// `UIStoryboard(name: "Welcome", bundle: ...)`
    static func welcome(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.welcome)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try bibleStudy.validate()
      try giving.validate()
      try launchScreen.validate()
      try liveStream.validate()
      try main.validate()
      try more.validate()
      try welcome.validate()
    }
    
    struct bibleStudy: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "BibleStudy"
      
      static func validate() throws {
        if UIKit.UIImage(named: "nav-discover", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'nav-discover' is used in storyboard 'BibleStudy', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct giving: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Giving"
      
      static func validate() throws {
        if UIKit.UIImage(named: "next", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'next' is used in storyboard 'Giving', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "church_logo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'church_logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct liveStream: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "LiveStream"
      
      static func validate() throws {
        if UIKit.UIImage(named: "profile_more", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'profile_more' is used in storyboard 'LiveStream', but couldn't be loaded.") }
        if UIKit.UIImage(named: "profilepic_more", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'profilepic_more' is used in storyboard 'LiveStream', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AnimatedViewController
      
      let animated = StoryboardViewControllerResource<AnimatedViewController>(identifier: "animated")
      let bundle = R.hostingBundle
      let main = StoryboardViewControllerResource<MainViewController>(identifier: "main")
      let name = "Main"
      
      func animated(_: Void = ()) -> AnimatedViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: animated)
      }
      
      func main(_: Void = ()) -> MainViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: main)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "church_logo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'church_logo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "fire", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'fire' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().animated() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'animated' could not be loaded from storyboard 'Main' as 'AnimatedViewController'.") }
        if _R.storyboard.main().main() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'main' could not be loaded from storyboard 'Main' as 'MainViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct more: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "More"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct welcome: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Welcome"
      
      static func validate() throws {
        if UIKit.UIImage(named: "back", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'back' is used in storyboard 'Welcome', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "darkPurple", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'darkPurple' is used in storyboard 'Welcome', but couldn't be loaded.") }
          if UIKit.UIColor(named: "goldenYellow", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'goldenYellow' is used in storyboard 'Welcome', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
